### PR TITLE
444 bytes

### PR DESCRIPTION
**Pull request by p01**

### CODE REVIEW

**Comment by aemkei** [comment]
@p01: This looks GREAT! But unfortunately we can't merge. Looks this will break it: https://github.com/codegolf/pac-man/commit/c9fa87f9427e0d35a4e8ffe295ea8a7d73d916fb#diff-eacf331f0ffc35d4b482f1d15a887d3b

**Comment by p01** [comment]
With a bit of gymnastic, we can get rid of the `.replace(/1/g,4).replace(/0/g,2)`, preferably using `0`for the walls to replace all the `&4` by a `!` or even better turning all the `4&l[index]?foo:bar` into `l[index]?bar:foo`. That should yield a 32-40 bytes saving!

**Comment by aemkei** [comment]
Was hoping to get rid of that! But it is a bit late for gymnastic for today. Hope to find some time the next days. // cc @maettig

**Comment by p01** [comment]
Alright! How about 438b based on the current master then ?

```
<pre id=p><script>l="";for(i in L=[a=8191,b=4161,c=5981,d=5125,5493,5397,5589,d,c,b,a])l+=L[i].toString(2).replace(/1/g,4).replace(/0/g,2)+3;l=l.split(""),w=14,x=76,X=48,d=k=D=!setInterval(onkeydown=function(a){for(a&&(k=a.which,Q),l[x]=0,8&l[x+=d=k-37>>2||4&l[x+(o=k%2?k-38:k*w-546)]?4&l[x+d]?0:d:o],l[x]=1,l[X]&=7,h=D%4,h=x-X?h%2?h-2:h*w-14:0,4&l[X+h]?D++:X+=h,l[X]|=8,h=i=0;153>i;)h+=" o.\n#   xxx"[l[++i]];p.innerHTML=h},250)</script>
```

**Comment by aemkei** [comment]
Looks like the collision detection for ghost and player does not work when both are moving. Thanks for all the suggestions! Need some sleep now …

(–.–) .zZ(101)

**Comment by aemkei** [comment]
WHOOT!: That late night gymnastic was worth the effort!

**Pull request closed without merging**
